version: "3.2"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /app/keycloakConfig/realm.json
    ports:
      - 8081:8080
    volumes:
      - ./config/keycloak:/app/keycloakConfig
  registrationprocess:
    build: build/docker
    ports:
      - 8080:8080
    depends_on:
      - keycloak