camunda.bpm:
  admin-user:
    id: demo
    password: demo
  filter:
    create: All tasks
    history-level: full
  metrics:
    enabled: true

keycloak:
  #this is a workaround(docker-compose specific url), docker-compose should override this variable
  serverUrl: http://keycloak:8080/auth
  realm: master
  usersRealm: Users
  clientId: admin-cli
  username: admin
  password: admin